CREATE TYPE "BlocagePhotoRole" AS ENUM ('DEPART', 'BLOCAGE');
ALTER TABLE "Blocage" ADD COLUMN "startX" DOUBLE PRECISION,
ADD COLUMN "startY" DOUBLE PRECISION,
ADD COLUMN "endX" DOUBLE PRECISION,
ADD COLUMN "endY" DOUBLE PRECISION,
ADD COLUMN "startGpsLat" DOUBLE PRECISION,
ADD COLUMN "startGpsLng" DOUBLE PRECISION,
ADD COLUMN "startGpsAccuracy" DOUBLE PRECISION,
ADD COLUMN "endGpsLat" DOUBLE PRECISION,
ADD COLUMN "endGpsLng" DOUBLE PRECISION,
ADD COLUMN "endGpsAccuracy" DOUBLE PRECISION,
ADD COLUMN "distanceMeters" DOUBLE PRECISION;
ALTER TABLE "Photo" ADD COLUMN "blocageRole" "BlocagePhotoRole";
UPDATE "Photo" SET "blocageRole" = 'BLOCAGE' WHERE "blocageId" IS NOT NULL;
