ALTER TABLE "Organization" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "legalName" TEXT,
ADD COLUMN "logoPath" TEXT,
ADD COLUMN "address" TEXT,
ADD COLUMN "postalCode" TEXT,
ADD COLUMN "city" TEXT,
ADD COLUMN "country" TEXT,
ADD COLUMN "phone" TEXT,
ADD COLUMN "contactEmail" TEXT,
ADD COLUMN "notificationEmail" TEXT,
ADD COLUMN "responsibleName" TEXT,
ADD COLUMN "website" TEXT,
ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'Europe/Paris',
ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'fr-FR',
ADD COLUMN "notificationPreferences" JSONB NOT NULL DEFAULT '{}';
