import { FormEvent, useEffect, useState } from "react";
import { UserDTO, UserRole } from "@proactif-field/shared";
import { useCreateUser, useDeleteUser, useResendUserInvitation, useUpdateUser, useUsers } from "../api/hooks";
import { useAuthStore } from "../auth/store";
import { ApiError } from "../api/client";
import Icon from "../components/Icon";

export default function AdminUsersPage() {
  const { data: users, isLoading } = useUsers(); const createUser = useCreateUser(); const updateUser = useUpdateUser(); const deleteUser = useDeleteUser(); const resendInvitation = useResendUserInvitation(); const currentUser = useAuthStore((state) => state.user);
  const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState<UserDTO | null>(null); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [employerCompany, setEmployerCompany] = useState(""); const [role, setRole] = useState<UserRole>(UserRole.TECHNICIEN); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); try { await createUser.mutateAsync({ name, email, phone: phone || undefined, employerCompany: employerCompany || undefined, role }); setName(""); setEmail(""); setPhone(""); setEmployerCompany(""); setRole(UserRole.TECHNICIEN); setShowForm(false); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Erreur lors de l’envoi"); } }
  return <><div className="topbar"><h1>Utilisateurs</h1></div><div className="page users-page">
    <button className="btn block" onClick={() => setShowForm((value) => !value)} style={{ marginBottom: 16 }}>{showForm ? "Annuler" : "+ Inviter un utilisateur"}</button>
    {showForm && <form onSubmit={submit} className="card user-invite-form">{error && <div className="error-banner">{error}</div>}<div className="user-form-grid"><Field label="Nom *" value={name} onChange={setName} required /><Field label="Email *" value={email} onChange={setEmail} type="email" required /><Field label="Téléphone" value={phone} onChange={setPhone} type="tel" /><Field label="Entreprise employeuse" value={employerCompany} onChange={setEmployerCompany} /><label className="field"><span>Rôle</span><select value={role} onChange={(event) => setRole(event.target.value as UserRole)}><option value={UserRole.TECHNICIEN}>Technicien</option><option value={UserRole.ADMIN}>Admin</option></select></label></div><p>Le destinataire recevra un lien personnel valable 48 heures pour choisir son mot de passe.</p><button className="btn block" type="submit" disabled={createUser.isPending}>{createUser.isPending ? "Envoi…" : "Envoyer l’invitation"}</button></form>}
    {isLoading && <p>Chargement…</p>}
    <div className="user-list">{users?.map((user) => <article key={user.id} className="card user-card user-card-clickable" onClick={() => setSelected(user)}><div className="user-card-person"><span className="account-avatar">{user.name.charAt(0).toUpperCase()}</span><div><h3>{user.name} {user.id === currentUser?.id && <small>(vous)</small>}</h3><p>{user.email}</p><small>{[user.phone, user.employerCompany].filter(Boolean).join(" · ") || "Informations professionnelles à compléter"}</small>{user.invitationPending && <span className="user-invite-status">Invitation en attente</span>}</div></div><div className="user-card-actions" onClick={(event) => event.stopPropagation()}>{user.invitationPending && <button className="btn secondary" onClick={() => resendInvitation.mutate(user.id)}>Relancer</button>}<span className={`user-role-badge ${user.role}`}>{user.role === UserRole.TECHNICIEN ? "Technicien" : "Admin"}</span><span className={`user-state ${user.isActive ? "active" : "inactive"}`}>{user.invitationPending ? "En attente" : user.isActive ? "Actif" : "Désactivé"}</span><button className="btn secondary" onClick={() => setSelected(user)}>Voir la fiche</button></div></article>)}</div>
    {selected && <UserDetail user={selected} isSelf={selected.id === currentUser?.id} onClose={() => setSelected(null)} onUpdate={async (input) => { const updated = await updateUser.mutateAsync({ id: selected.id, input }); setSelected(updated); }} onDelete={async () => { if (!confirm(`Supprimer le compte de ${selected.name} ? Cette personne perdra immédiatement son accès.`)) return; await deleteUser.mutateAsync(selected.id); setSelected(null); }} />}
  </div></>;
}

function UserDetail({ user, isSelf, onClose, onUpdate, onDelete }: { user: UserDTO; isSelf: boolean; onClose: () => void; onUpdate: (input: { name?: string; phone?: string | null; employerCompany?: string | null; role?: UserRole; isActive?: boolean }) => Promise<void>; onDelete: () => Promise<void> }) {
  const [name, setName] = useState(user.name); const [phone, setPhone] = useState(user.phone ?? ""); const [company, setCompany] = useState(user.employerCompany ?? ""); const [role, setRole] = useState(user.role); const [saving, setSaving] = useState(false);
  useEffect(() => { setName(user.name); setPhone(user.phone ?? ""); setCompany(user.employerCompany ?? ""); setRole(user.role); }, [user]);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); try { await onUpdate({ name, phone: phone || null, employerCompany: company || null, role }); } finally { setSaving(false); } }
  return <div className="sheet-overlay" onClick={onClose}><aside className="sheet user-detail" onClick={(event) => event.stopPropagation()}><header><div><span>Fiche utilisateur</span><h2>{user.name}</h2></div><button onClick={onClose} aria-label="Fermer"><Icon name="close" /></button></header><form onSubmit={save}><Field label="Nom" value={name} onChange={setName} required /><Field label="E-mail de connexion" value={user.email} onChange={() => undefined} type="email" disabled /><Field label="Téléphone" value={phone} onChange={setPhone} type="tel" /><Field label="Entreprise employeuse" value={company} onChange={setCompany} /><label className="field"><span>Rôle</span><select value={role} disabled={isSelf} onChange={(event) => setRole(event.target.value as UserRole)}><option value={UserRole.TECHNICIEN}>Technicien</option><option value={UserRole.ADMIN}>Admin</option></select></label><dl className="user-detail-meta"><div><dt>État</dt><dd>{user.invitationPending ? "Invitation en attente" : user.isActive ? "Compte actif" : "Compte désactivé"}</dd></div><div><dt>Créé le</dt><dd>{new Date(user.createdAt).toLocaleDateString("fr-FR")}</dd></div></dl><button className="btn block" disabled={saving}>{saving ? "Enregistrement…" : "Enregistrer la fiche"}</button></form><div className="user-detail-actions">{!user.invitationPending && <button className="btn secondary block" disabled={isSelf} onClick={() => onUpdate({ isActive: !user.isActive })}>{user.isActive ? "Désactiver le compte" : "Réactiver le compte"}</button>}<button className="btn danger block" disabled={isSelf} onClick={() => void onDelete()}>Supprimer définitivement l’accès</button></div></aside></div>;
}

function Field({ label, value, onChange, type = "text", required = false, disabled = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; disabled?: boolean }) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} disabled={disabled} /></label>; }
